import "@/styles/globals.css";

import { inter } from "@/styles/fonts";

export const metadata = {
  title: "Design Challenge - Arrival Identity System",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/public/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>{children}</body>
    </html>
  );
}
